@baseUrl = http://localhost:3000

### Register a new user
POST {{baseUrl}}/api/register
Content-Type: application/json

{
  "name": "John Doe",
  "password": "password123"
}

###

### Log in with the registered user
# @name login
POST {{baseUrl}}/api/login
Content-Type: application/json

{
  "name": "John Doe",
  "password": "password123"
}

###

### Extract the authentication token from the login response
@authToken = {{login.response.body.token}}

###


### Log out the current user
DELETE {{baseUrl}}/api/logout
Authorization: Bearer {{authToken}}

###

### Access protected resource: Get Rooms
GET {{baseUrl}}/api/rooms
Authorization: Bearer {{authToken}}

###

### Log out the current user
DELETE {{baseUrl}}/api/logout
Authorization: Bearer {{authToken}}

###
