### Login
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "name": "John Doe",
  "password": "password123"
}
> {%
    client.global.set("auth_token", response.body.user.auth_token);
%}

### Logout
DELETE http://localhost:3000/api/logout
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Register
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "name": "John Doe",
  "password": "password123"
}
> {%
    client.global.set("auth_token", response.body.user.auth_token);
%}
