@baseUrl = http://localhost:3000

### Register a new user
POST {{baseUrl}}/api/register
Content-Type: application/json

{
  "name": "John Doe",
  "password": "password123"
}

###

### Log in with the registered user
# @name login
POST {{baseUrl}}/api/login
Content-Type: application/json

{
  "name": "John Doe",
  "password": "password123"
}

###

### Extract the authentication token from the login response
@authToken = {{login.response.body.token}}

###

### Register a new user as another user
POST {{baseUrl}}/api/register
Content-Type: application/json

{
  "name": "Another User Doe",
  "password": "password123"
}

###

### Log in with the registered user
# @name login
POST {{baseUrl}}/api/login
Content-Type: application/json

{
  "name": "Another User Doe",
  "password": "password123"
}

###

### Extract the authentication token from the login response
@authToken = {{login.response.body.token}}

###


### Log out the current user
DELETE {{baseUrl}}/api/logout
Authorization: Bearer {{authToken}}

###


### Access protected resource: Create Room
POST {{baseUrl}}/api/rooms
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Room Global",
  "public": true
}

### Access protected resource: Get Rooms
GET {{baseUrl}}/api/rooms
Authorization: Bearer {{authToken}}

###

### Access protected resource: Search Room
GET {{baseUrl}}/api/rooms?search=Room%20Global
Authorization: Bearer {{authToken}}

###

### Access protected resource: Get Room by ID
# @name room
GET {{baseUrl}}/api/rooms/1
Authorization: Bearer {{authToken}}

###

### Extract the authentication token from the login response
@inviteCode = {{room.response.body.invite_code}}

###

### Access protected resource: Join Room
POST {{baseUrl}}/api/rooms/1/join
Authorization: Bearer {{authToken}}

###

### Access protected resource: Join Room with invite code
GET {{baseUrl}}/api/rooms/invite?invite_code={{inviteCode}}
Authorization: Bearer {{authToken}}
Content-Type: application/json


### Access protected resource: Leave Room
DELETE {{baseUrl}}/api/rooms/1/leave
Authorization: Bearer {{authToken}}

###

### Access protected resource: Update Room
PUT {{baseUrl}}/api/rooms/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Room Global Updated"
}

### Access protected resource: Delete Room
DELETE {{baseUrl}}/api/rooms/1
Authorization: Bearer {{authToken}}

###

### Access protected resource: Create Message
POST {{baseUrl}}/api/rooms/1/messages
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "content": "Hello, Welcome to the room!"
}

###

### Access protected resource: Create Message
POST {{baseUrl}}/api/rooms/1/messages
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "content": "Hello, Welcome to the room! This is a test message."
}

### Access protected resource: Get Messages
GET {{baseUrl}}/api/rooms/1/messages
Authorization: Bearer {{authToken}}

###

### Access protected resource: Get Messages with pagination
GET {{baseUrl}}/api/rooms/1/messages?page=1&per_page=10
Authorization: Bearer {{authToken}}

###
