services:
  chat-nuxt:
    image: syaifudin16/chat-nuxt:latest
    environment:
      - NUXT_PUBLIC_API_BASE=https://chat-server.udin.web.id
      - NUXT_PUBLIC_WEBSOCKET_HOST=ws://chat-server.udin.web.id/cable
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - chat-server

  chat-server:
    image: syaifudin16/chat-server:latest
    environment:
      - RAILS_ENV=production
      - PORT=3000
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    ports:
      - "3000:3000"

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - chat-nuxt
      - chat-server

volumes:
  caddy_data:
  caddy_config:
